### ISSUE TITLE
 Free trial data deletion --> Free trial / Paid subscription data deletion

### ISSUE THREAD

**Issue by marcender** [NetAppDocs/saasbackupO365#102]
Page: [Free trial data deletion](https://docs.netapp.com/us-en/saasbackupO365/reference_free_trial_data.html)

Please add some text about the paid license / subscription, what happens when a customer leaves a subscriptions. what happens to it's data and which regulation we meet.

Thanks Marc

**Comment by netapp-rlithman** [comment]
Hi Marc, 

Thanks for bringing this to our attention. I have reached out to you and the team to work on this issue.

**Comment by netapp-rlithman** [comment]
I have added a new topic "Paid subscription data deletion" to address the issue. 

https://docs.netapp.com/us-en/saasbackupO365/reference_paid_subscription_data.html
