### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by mhparker44** [NetAppDocs/saasbackupO365#118]
Page: [New features and updates](https://docs.netapp.com/us-en/saasbackupO365/reference_new_saasbackupO365.html)

"May 2019
SaaS Backup now supports add-on licenses.

Activating an add-on license"

This link doesn't work. I believe the correct link is: https://docs.netapp.com/us-en/saasbackupO365/task_updating_subscription_information.html

**Comment by netapp-rlithman** [comment]
The link is fixed now. Thanks for letting me know, Matthew!
