### ISSUE TITLE
Text Change Request for Disclaimer

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/saasbackupO365#125]
Page: [NetApp SaaS Backup for Microsoft 365 のドキュメント](https://docs.netapp.com/ja-jp/saasbackupO365/index.html)

Hi Aksel and all,
Having increased requirement for the disclaimer, Legal Manager and I discussed and decided to request 2 things to make the message clearer.  One of them is the change of the text for Disclaimer:

•	Current Message:
NetAppは、業界をリードするニューラル機械翻訳ツールを利用して、このコンテンツを提供しています。
(NetApp provides with the content using industry-leading Neural Machine Translation tool.)
•	New Message:
日本語は機械翻訳による参考訳です。内容に矛盾や不一致があった場合には、英語の内容が優先されます。
(Japanese is provided using machine translation for your convenience. English precedes Japanese for any inconsistencies.) 

Can you please replace it to the new one?

Thanks,
Yuka

**Comment by netapp-rlithman** [comment]
Hi Yuka, 

Thanks for pointing this out. 

@akseldavis - Could you update this? If not, could you let me know who can help? 

Best, 
Rachel

**Comment by yukakou** [comment]
What is the status for this issue now? Please let me know.

**Comment by netapp-rlithman** [comment]
Addressed with production team.
