### ISSUE TITLE
Format Change Request for Disclaimer

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/saasbackupO365#126]
Hi Aksel and all,

Having increased requirement for the disclaimer, Legal Manager and I discussed and decided to request 2 things to make the message clearer. Here is the second request - can it be shown as the fixed text instead of Tooltip?

We are afraid the information in the tooltip might be missed as it cannot be displayed if the users don’t hover the mouse over “I” icon.
Can it be made to a fixed text instead of being hidden in the tooltip window?

For your reference, I found that AWS started to publish their product manuals online in 10 languages with the Disclaimer about MT, and their Disclaimer text is always shown.
https://docs.aws.amazon.com/ja_jp/aws-backup/latest/devguide/whatisbackup.html
 
<img width="488" alt="AWS_document" src="https://user-images.githubusercontent.com/50446078/114146757-f0211500-9952-11eb-8c01-02acdedb853f.png">

Hope this is something possible for our GitHub content, too.

Thanks,
- Yuka

**Comment by netapp-rlithman** [comment]
Hi Yuka,

Thanks for pointing this out and giving us some tips. 

@akseldavis - Could you update this? If not, could you let me know who can help?

Best,
Rachel

**Comment by akseldavis** [comment]
Hi Yuka, 
I'm creating an internal issue to track this request. The request will be triaged for prioritization, and we will respond internally on a decision.

**Comment by yukakou** [comment]
May I ask you how this legal request is being handled?

**Comment by netapp-rlithman** [comment]
Addressed with production team.
