### ISSUE TITLE
Better to update the image

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/saasbackupO365#127]
Page: [NetApp SaaS Backup for Microsoft 365 Overview](https://docs.netapp.com/us-en/saasbackupO365/concept_overview.html)

Hi current image shows an storage as a destination of backup data.
Should be better to avoid confusion and change the graphic with an updated one.

**Comment by netapp-rlithman** [comment]
Hi Gabriel, 

Thanks for letting us know. I'll ask the product team for their input to address the issue. 

Best, 
Rachel

**Comment by netapp-rlithman** [comment]
The image has been updated. Thank you again for bringing it to our attention, Gabriel. 

Page: [NetApp SaaS Backup for Microsoft 365 Overview](https://docs.netapp.com/us-en/saasbackupO365/concept_overview.html)
