### ISSUE TITLE
Add more content for 2021 - whats new page

### ISSUE THREAD

**Issue by marcender** [NetAppDocs/saasbackupO365#131]
Page: [New features and updates](https://docs.netapp.com/us-en/saasbackupO365/reference_new_saasbackupO365.html)
is there no change since December 2020 in SaaS backup? Please add more content and let us know what's new.
like Advanced Search or other.

**Comment by netapp-rlithman** [comment]
Hi Marc. Thank you as always for your support on keeping our docs healthy!  

I am awaiting information regarding new features and updates. Between December 2020 and now, the documentation has undergone minor updates but nothing related to new features. I am working on a feature update this month, so you should see something relatively soon. 

I can add that the documentation architecture and page titles were updated as you can see on the left side navigation bar. Page titles beginning with verbs used to be gerunds like "Performing a search". These are now in imperative form to aid localization efforts (Ex: Perform a search). 

[Use Advanced Search](https://docs.netapp.com/us-en/saasbackupO365/task_using_advanced_search.html) is a new page with content separated from [Perform a search](https://docs.netapp.com/us-en/saasbackupO365/task_performing_search.html). The [Perform a search](https://docs.netapp.com/us-en/saasbackupO365/task_performing_search.html) content has been simplified.
