### ISSUE TITLE
Instructions on how to create a support ticket

### ISSUE THREAD

**Issue by mhparker44** [NetAppDocs/saasbackupO365#133]
Page: [Activate support](https://docs.netapp.com/us-en/saasbackupO365/task_activate_support.html)

Could we add a page which shows how to create a support ticket? Existing customers know how to use mysupport.netapp.com, but new customers do not.
We have in the docs to contact saasbackupsupport@netapp.com (or something similar), but this is NOT the preferred route according to the engineering team.

Best route is to:
Log into mysupport.netapp.com, create a new ticket using Serial Number.

**Comment by netapp-rlithman** [comment]
Hi Matthew. Thanks for pointing this out. I think the best course of action is to change the instructions on the [Where to get help and find more information](https://docs.netapp.com/us-en/saasbackupO365/concept_get_help_find_info.html) page. Could you provide more details about using the serial number?

**Comment by netapp-rlithman** [comment]
It's been determined that we won't be updating this content. Thanks again. If you have any questions, please follow up with me.
