### ISSUE TITLE
Global Admin Permissions temporarily needed on Service Account for this to work.

### ISSUE THREAD

**Issue by mhparker44** [NetAppDocs/saasbackupO365#144]
Page: [Enable Modern Authentication](https://docs.netapp.com/us-en/saasbackupO365/task_enable_modern_authentication.html)

**Comment by netapp-rlithman** [comment]
Hi Matthew,

Thank you for bringing this to our attention. We are looking into it and determining how best to address it.

Thanks again for helping us improve the quality of our documentation.

Rachel Lithman
Technical writer
NetApp Information Engineering (IE) Content Services

**Comment by netapp-rlithman** [comment]
I added a note to the page to share the information you requested with our customers. Thanks again for your help, Matthew.

See the updated page - [Enable Modern Authentication](https://docs.netapp.com/us-en/saasbackupO365/task_enable_modern_authentication.html).
