### ISSUE TITLE
Retention periods

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/saasbackupO365#15]
Page: [Managing backups with NetApp SaaS Backup for Office 365](https://docs.netapp.com/us-en/saasbackupO365/task_managing_backups.html)

Hi, just wondering when this documentation will be updated with the latest release (July 2018)?
For example, the retention periods have been updated but it doesn't look like the documentation has been.

**Comment by netapp-aherbin** [comment]
Thanks for your feedback. We expect to publish updates to the SaaS Backup documentation in the next several days.
