### ISSUE TITLE
There's a typo in the TOC

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/saasbackupO365#32]
Page: [Managing restores with NetApp SaaS Backup for Office 365](https://docs.netapp.com/us-en/saasbackupO365/task_managing_restores.html)

The title on this page is correct, but the TOC has "Mananging" instead of "Managing" for this specific page.

**Comment by netapp-aherbin** [comment]
Typo has been corrected.  Thank you for your comment.
