### ISSUE TITLE
Missing information about O365 admin account setup for free-trial

### ISSUE THREAD

**Issue by helpium** [NetAppDocs/saasbackupO365#38]
Page: [Getting started with NetApp SaaS Backup for Office 365](https://docs.netapp.com/us-en/saasbackupO365/task_getting_started_free_trial.html)

The information "Creating a new MS Office 365 service account with global administrator permissions" and following are missing in the Free-Trial documentation.

**Comment by netapp-aherbin** [comment]
Thank you for your comment.  I'm addressing this with the team and will have an update shortly.

**Comment by netapp-aherbin** [comment]
Creating a MS Office service account with global permissions has been added to the free trial workflow.
