### ISSUE TITLE
What does support give me?

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/saasbackupO365#49]
Page: [Activating support](https://docs.netapp.com/us-en/saasbackupO365/task_activate_support.html)

Hi, while I like this page that talks about support - I'd like to see what support actually provides if I activate it (and what happens if i opt NOT to activate it?)

Thanks!

**Comment by netapp-aherbin** [comment]
Activating support enables you to access technical support over the phone, online chat, or web ticketing system. If support is not activated, you cannot access these support channels.

We've updated the documentation to clarify this.
