### ISSUE TITLE
Improvement ideas for Viewing deprovisioned and purged data

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/saasbackupO365#53]
Hi!
Some improvement ideas for:
Page: [Viewing deprovisioned and purged data](https://docs.netapp.com/us-en/saasbackupO365/task_viewing_deprovisioned.html)

Left menu text says "Viewing deprovisioned items" but the page title is "Viewing deprovisioned and purged data" and contains 2 sections "Viewing a list deprovisioned accounts" and "Viewing a list of purged data".
Users that look for purged data will not find this page through the left menu and users that look for deprovisioned items may think that only accounts can be in deprovisioned status.

IMPROVEMENT PROPOSAL:
A.1) Divide "task_viewing_deprovisioned.adoc" file into "task_viewing_deprovisioned.adoc" containing the "Viewing a list deprovisioned accounts" part.
A.2) Keep "Viewing deprovisioned items" left menu that will link to only first part of the page "task_viewing_deprovisioned.adoc".
A.3) Change the manual page title from "Viewing a list deprovisioned accounts" to "Viewing the list of deprovisioned items".
A.4) Change step 2 description to "Click the number of unprotected items at the desired service.".

B.1) Create a new file "task_viewing_purged.adoc" containing the second part of "Viewing a list of purged data".
B.2) Add "Viewing the list of purged data" left menu that will link only to the second part of the new page "task_viewing_purged.adoc".
B.3) Change "Viewing a list of purged data" title to "Viewing the list of purged data".

Or, at least, change current "Click the number of mailboxes." to "Click the number of unprotected items at the desired service.".

Hope it helps. Regards,
Gabriel

**Comment by netapp-rlithman** [comment]
Hi Gabriel!

Thanks so much for your detailed feedback and suggestions. I'm looking into the issue now. 

Best, 
Rachel

**Comment by netapp-rlithman** [comment]
I have updated the documentation using your suggestions. Thank you again!

**Comment by gabrieltokyo** [comment]
It looks great!
Thank you.
