### ISSUE TITLE
Need additional restrictions listed

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/saasbackupO365#75]
Page: [Free trial restrictions](https://docs.netapp.com/us-en/saasbackupO365/concept_free_trial_restrictions.html)

- Can we add that Teams is disabled by default and only enabled upon request?
- Also, that to enable Teams all O365 users must be SaaS Backup licensed users?

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  I'm validating this information and will post an update soon.

**Comment by jenatnetapp** [comment]
Hi Amanda, 

Did we ever get closure on this one?

Thanks, 
Jennifer

**Comment by netapp-rlithman** [comment]
I have updated [Free trial restrictions](https://docs.netapp.com/us-en/saasbackupO365/concept_free_trial_restrictions.html). Thanks randobrando46 for keeping our docs healthy!
