### ISSUE TITLE
"Share mailboxes" makes the info hard to find

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/saasbackupO365#76]
Page: [Releasing a user license](https://docs.netapp.com/us-en/saasbackupO365/task_releasing_a_user_license.html)

People usually search for "shared" mailboxes, not "share mailboxes", and MS calls them "shared" as wel ([1]) and then can't find the info on whether licenses required for them. 

I'd like to see the word "shared" added somewhere in that page, or "share mailboxes" changed to "shared mailboxes".

[1] https://duckduckgo.com/?t=lm&q=Shared+mailboxes&ia=web

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  This is a typo.  I should be "shared" and has been updated.
