### ISSUE TITLE
Feedback from Phoebe Goh - The question of SaaS Backup for O365

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/saasbackupO365#78]
Page: [NetApp SaaS Backup for Office 365 documentation](https://docs.netapp.com/us-en/saasbackupO365/index.html)

From: Goh, Phoebe <Phoebe.Goh@netapp.com> 
Sent: 09 July 2020 19:28
To: ng-doccomments <ng-doccomments@netapp.com>
Cc: Boluda Lopez, Gabriel <Gabi.Boluda@netapp.com>
Subject: Fwd: The question of SaaS Backup for O365

Hi Docs team,

Is there some way we could have the following information added to the SaaS Backup for O365 documentation?

•	 Licenses supported and determining what will be protected (it’s pretty obvious but IMO good to include in our docs. e.g. if you have an application license it can get backed up
•	Where to find private channels
•	Not sure if Teams chat has been updated in the docs - clarity on what is backed up in Teams

Thought I would forward this to you as I think it’s important to get the right information in our external facing documentation. (cc Gabi as this has come out of a Japanese customer conversation)

Phoebe

**Comment by netapp-aherbin** [comment]
Hi Phoebe,

Thank you for your feedback.  I'll be working on adding clarity around these areas. I'll let you know when we get an update posted.

Amanda

**Comment by netapp-rlithman** [comment]
Hi Phoebe, 

Thank you for contacting us with requests for documentation updates. I'm looking into the first two bullet points you listed with the product team. 

For the last bullet you listed, backups for TeamsChat has information on the following pages: 

[Release notes (March/April 2020)](https://docs.netapp.com/us-en/saasbackupO365/reference_new_saasbackupO365.html#marchapril-2020)
[Performing an immediate backup of a service](https://docs.netapp.com/us-en/saasbackupO365/task_performing_immediate_backup_of_service.html)

Is this what you were looking for your third bullet point? If not, could you follow up? 

Thanks, 
Rachel

**Comment by netapp-rlithman** [comment]
Hi Phoebe, 

We added a topic in the documentation called "Locating Teams data" under Managing Backups to address this issue. You can find the link [here](https://docs.netapp.com/us-en/saasbackupO365/reference_teams_data_locations.html). I hope this helps. 

Best, 
Rachel

**Comment by netapp-rlithman** [comment]
The following page has information about restores and where to find restored data. It also includes links to high-level and granular-level restore topics for all services with where to find restored data. Teams data is included. 

Page: [About restores](https://docs.netapp.com/us-en/saasbackupO365/reference_about_restores.html)
